louvre_resa_home:
    path:     /
    defaults: { _controller: ARLouvreBundle:Resa:initialiserReservation }

louvre_resa_initialiser:
    path:     /initialiser-reservation
    defaults: { _controller: ARLouvreBundle:Resa:initialiserReservation }

louvre_resa_completer:
    path:    /completer-reservation
    defaults: { _controller: ARLouvreBundle:Resa:completerReservation }

louvre_resa_voir:
    path:    /voir-reservation
    defaults: { _controller: ARLouvreBundle:Resa:voirReservation }

louvre_resa_rechercher:
    path:    /rechercher-reservation
    defaults: { _controller: ARLouvreBundle:Resa:rechercherReservation}

louvre_payment_checkout:
    path:    /checkout
    defaults: {  _controller: ARLouvreBundle:Payment:checkout}