services:
    ar_louvre.outilsbillets:
        class: AR\LouvreBundle\Services\OutilsBillets\AROutilsBillets
        arguments:
            - '%age_max_gratuit%'
            - '%age_max_enfant%'
            - '%tarif_enfant%'
            - '%age_min_senior%'
            - '%tarif_senior%'
            - '%tarif_normal%'
            - '%tarif_reduit%'

    ar_louvre.outilsresa:
        class: AR\LouvreBundle\Services\OutilsResa\AROutilsResa
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ar_louvre.outilsbillets"
            - '@templating'
            - '@mailer'
            - '@session'

    ar_louvre.stripeclient:
        class: AR\LouvreBundle\Services\StripeClient\StripeClient
        autowire: true
        arguments:
            - '%stripe_secret_key%'
            - "@ar_louvre.outilsresa"

parameters:
    age_max_gratuit: 3
    age_max_enfant: 11
    tarif_enfant: 8
    age_min_senior: 60
    tarif_senior: 12
    tarif_normal: 16
    tarif_reduit: 10


