services:
    ar_louvre.outilsbillets:
        class: AR\LouvreBundle\Services\OutilsBillets\AROutilsBillets

    ar_louvre.outilsresa:
        class: AR\LouvreBundle\Services\OutilsResa\AROutilsResa
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ar_louvre.outilsbillets"

    ar_louvre.stripeclient:
        class: AR\LouvreBundle\Services\StripeClient\StripeClient
        autowire: true
        arguments:
            - '%stripe_secret_key%'


