services:
    ar_louvre.outilsbillets:
        class: AR\LouvreBundle\Services\OutilsBillets\AROutilsBillets
        arguments:
            - '%age_max_gratuit%'
            - '%age_max_enfant%'
            - '%tarif_enfant%'
            - '%age_min_senior%'
            - '%tarif_senior%'
            - '%tarif_normal%'
            - '%tarif_reduit%'

    ar_louvre.outilsresa:
        class: AR\LouvreBundle\Services\OutilsResa\AROutilsResa
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ar_louvre.outilsbillets"
            - '@templating'
            - '@mailer'
            - '@session'
            - '%heure_limite_demi_journee%'
            - '%nb_billets_dispo_par_jour%'

    ar_louvre.stripeclient:
        class: AR\LouvreBundle\Services\StripeClient\StripeClient
        autowire: true
        arguments:
            - '%stripe_secret_key%'
            - "@ar_louvre.outilsresa"



