louvre_resa_init:
    path:     /
    defaults: { _controller: LouvreBundle:Resa:init }

louvre_resa_fill:
    path:    /fill
    defaults: { _controller: LouvreBundle:Resa:fill }

louvre_resa_edit:
    path:    /edit
    defaults: { _controller: LouvreBundle:Resa:edit}
